package code.exam.repository;

import code.exam.db.DatabaseConnection;
import code.exam.model.Transaction;
import code.exam.model.TransactionType;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

@Repository
@RequiredArgsConstructor
public class TransactionRepository {

    private final DatabaseConnection databaseConnection;

    /**
     * POST /transaction
     * The id is generated by the service layer before calling this method.
     */
    public Transaction save(Transaction transaction) throws SQLException {
        String sql = """
                INSERT INTO transactions (id, account_id, created_at, transaction_type, amount, reason)
                VALUES (?, ?, ?, ?, ?, ?)
                """;

        try (Connection connection = databaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, transaction.getId());
            statement.setString(2, transaction.getAccountId());
            statement.setTimestamp(3, Timestamp.from(transaction.getCreatedAt()));
            statement.setString(4, transaction.getTransactionType().name());
            statement.setBigDecimal(5, transaction.getAmount());
            statement.setString(6, transaction.getReason());

            statement.executeUpdate();
        }

        return transaction;
    }

    /**
     * GET /transactions?type=in|out
     * If type is null, returns every transaction.
     */
    public List<Transaction> findAll(TransactionType type) throws SQLException {
        String sql = "SELECT id, account_id, created_at, transaction_type, amount, reason FROM transactions";
        if (type != null) {
            sql += " WHERE transaction_type = ?";
        }
        sql += " ORDER BY created_at DESC";

        try (Connection connection = databaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            if (type != null) {
                statement.setString(1, type.name());
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                return mapRows(resultSet);
            }
        }
    }

    /**
     * GET /accounts/{id}/transactions
     */
    public List<Transaction> findByAccountId(String accountId) throws SQLException {
        String sql = """
                SELECT id, account_id, created_at, transaction_type, amount, reason
                FROM transactions
                WHERE account_id = ?
                ORDER BY created_at DESC
                """;

        try (Connection connection = databaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, accountId);

            try (ResultSet resultSet = statement.executeQuery()) {
                return mapRows(resultSet);
            }
        }
    }

    /**
     * GET /account/{id}/balance
     * Computes (sum of IN) - (sum of OUT) directly in SQL.
     */
    public BigDecimal getBalanceByAccountId(String accountId) throws SQLException {
        String sql = """
                SELECT
                    COALESCE(SUM(CASE WHEN transaction_type = 'IN' THEN amount ELSE 0 END), 0)
                    - COALESCE(SUM(CASE WHEN transaction_type = 'OUT' THEN amount ELSE 0 END), 0) AS balance
                FROM transactions
                WHERE account_id = ?
                """;

        try (Connection connection = databaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, accountId);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getBigDecimal("balance");
                }
                return BigDecimal.ZERO;
            }
        }
    }

    private List<Transaction> mapRows(ResultSet resultSet) throws SQLException {
        List<Transaction> transactions = new ArrayList<>();
        while (resultSet.next()) {
            transactions.add(mapRow(resultSet));
        }
        return transactions;
    }

    private Transaction mapRow(ResultSet resultSet) throws SQLException {
        return Transaction.builder()
                .id(resultSet.getString("id"))
                .accountId(resultSet.getString("account_id"))
                .createdAt(resultSet.getTimestamp("created_at").toInstant())
                .transactionType(TransactionType.valueOf(resultSet.getString("transaction_type")))
                .amount(resultSet.getBigDecimal("amount"))
                .reason(resultSet.getString("reason"))
                .build();
    }
}